//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp27
{
    using System;
    using System.Collections.Generic;
    
    public partial class login1
    {
        public int log_id { get; set; }
        public string log_name { get; set; }
        public string log_pass { get; set; }
        public string log_role { get; set; }
    }
}
